language: cpp
os:
  - linux
  - osx
osx_image: xcode8.3

# Use Ubuntu 14.04 LTS (Trusty) as the Linux testing environment.
sudo: required
dist: trusty

# We check out glslang and SPIRV-Tools at specific revisions to avoid test output mismatches
env:
  - PROFILE=plain

before_script:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew upgrade python3; fi

script:
  - ./checkout_glslang_spirv_tools.sh
  - make -j2
  - ./test_shaders.sh
